### PR TITLE
Make methods fluent and also add more methods to class

### PR DESCRIPTION
**Pull request by mantey-github**
I added some methods to the Tabula Class and also made some of the methods fluent.

- `setPdf(string $input)`: This method accepts the PDF file which needs to be converted. It returns the `Tabula` class

- `setOptions(array $options)`: This method accepts an array of options. These options are the options required by `tabula`. 
Options by default are:
```
[
        'pages' => null,
        'guess' => true,
        'area' => [],
        'relativeArea' => false,
        'lattice' => false,
        'stream' => false,
        'password' => null,
        'silent' => false,
        'columns' => null,
        'format' => null,
        'batch' => null,
        'outfile' => null,
]
```

- `buildOptions(array $options)`: This now accepts are the options required by tabula in an array form. Now the method is `private`

- `buildJavaOptions()`: This method is currently `private`.

- `run()`: This method is currently `private`.

- `convert()`: This is the final method that has to be called to handle the conversion of the PDF file

### CODE REVIEW

**Comment by initred** [comment]
I'm sorry to see you late about the request.
Currently, the package has not been updated.
Also, thank you fr orequesting this fast-written code for the package that was left unattended.
I've read all the codes and it doesn't seem to be a problem.
We will merge and update that method.
I support you to be a good developer.
Thankyou.

**Comment by mantey-github** [comment]
> I'm sorry to see you late about the request.
> Currently, the package has not been updated.
> Also, thank you fr orequesting this fast-written code for the package that was left unattended.
> I've read all the codes and it doesn't seem to be a problem.
> We will merge and update that method.
> I support you to be a good developer.
> Thankyou.

you're welcome

**Comment by mantey-github** [comment]
> I'm sorry to see you late about the request.
> Currently, the package has not been updated.
> Also, thank you fr orequesting this fast-written code for the package that was left unattended.
> I've read all the codes and it doesn't seem to be a problem.
> We will merge and update that method.
> I support you to be a good developer.
> Thankyou.

I will create a pull request updating the README.md

**Review by initred — COMMENTED** [review]
At that time, I had no time, so I wrote all the codes in public. I remember. Haha. LOL. I'll take this into consideration.

**Pull request merged**
